### ISSUE TITLE
no recording

### ISSUE THREAD

**Issue by robinsandfort** [mcguirepr89/BirdNET-system#22]
Hi,
I would really love to get your system running on a raspy 4:

birdlog.local states:
birdnet_analysis.sh[4010]: find: ´/home/pi/BirdSongs/September-2021/25-Saturday´: No such file or directory

It seems it is not recording any files
The usb mic is on hw:3 might this be the problem?
What exactly do I have to state in the birdnet.conf:
REC_CARD= "number or name?"

Thank you so much,
Robin

**Comment by mcguirepr89** [comment]
Hi, Robin
Thank you so much for your interest in the project. I think you're right in your hunch that the recordings aren't working.

To find out what's going on, I'd like to ask that you send me two files that the most recent installer spits out  when it has finished (or failed): `~/BirdNET-system/logs.tar.gz` and `~/BirdNET-system/soundcard_params.txt`.

If you don't see those files, i.e., installed BirdNET-system before that logging was in the _BirdNET-system-for-raspi4_ repo, then my recommendation would be to do a clean install using the most recent installer (I updated it last night around 8pm-9pm EST).

I'm happy to help and am sure we'll figure out what's going on to get your system up and running,

My best,
Patrick

**Comment by robinsandfort** [comment]
Hi Patrick,
thanks for your quick response. I just send you the two requested files. 
The USB microphones (one is an audiomoth with the new usb firmeware) are working on the raspi.
Thanks again for your help!

**Comment by mcguirepr89** [comment]
My pleasure to help out :) and thanks for the logs! They're a big help and, I believe, point us to the problem: my slouchy documentation in the _birdnet.conf-defaults_ file coupled with the _README.md_ not having any section (yet) for troubleshooting and my lack of access to varied microphone hardware.

- My Suspicion: The REC_CARD is set to "REC_CARD='Blue Snowball'", which isn't what we want here. (I apologize for not seeing your question in the original post regarding the REC_CARD variable setting.)
- What is needed: The REC_CARD should be set to the output of `aplay -L | grep dsnoop | cut -d, -f1 | grep -ve 'vc4' -e 'Head' -e 'PCH' | uniq`, but I think that your logs might suggest I change that constricting setting to be more device-agnostic. Read on to see what direction I'm hoping to go.

To explain how this ambiguity came to be: 
In an effort to abstract the USB microphone settings to work for most folks, the variable is usually automatically set during installation with the long string of piped commands:`sudo -u pi aplay -L | grep dsnoop | cut -d, -f1 | grep -ve 'vc4' -e 'Head' -e 'PCH' | uniq`  
\- ((Irrelevant note: I know `awk` can do most of that much more elegantly, but for some reason, I've been having a hard time getting `awk` to play nicely with the `heredoc` that ultimately installs the _birdnet.conf_ file, hence the `grep`s and `cut`.))

- `sudo -u pi aplay -L`: output all PCM devices the pi user can access
- `grep dsnoop`:filter those results to only show the dsnoop capable devices (for sharing the audio stream between the _birdnet_recording.service_ and the _livestream.service_)
- `cut -d, -f1`: using a comma "," as the delimiter,  print the first field of the results
- `grep -ve 'vc4' -e 'Head' -e 'PCH'`:remove the Headphones soundcard (since it does not support input) and the HDMI soundcard (to leave only the USB interface cards)
- `uniq`:in case the microphone has created multiple dnsoop devices that fit those qualifications, do not show any duplicates

Once that was put in place, I removed most of the rest of that pipe in the comments for the REC_CARD variable in the _birdnet.conf-defaults_ file. But, I was unclear in the documentation on how to parse the output of `aplay -L` in order to set that variable properly, so it seems you did what makes sense in putting the device name there. My slouchy documentation just says:

> \## If you would like to use a different microphone than
> \## what this produces, or if your microphone does not support creating a
> \## dsnoop device, you can set this explicitly from a list of the available
> \## devices from the output of running 'aplay -L'

\- Note: a properly set REC_CARD value will also affect the CHANNELS variable that is automatically created during installation.

But tinkering around and seeing your results gave me another thought: I ought to just use the pulse server that is included to handle abstracting the stream instead of counting on the microphone to do the abstraction layer.

If you can help me test this theory, we may be onto something good. If you don't mind, please alter your _birdnet.conf_ to reflect the following:

1. Make the REC_CARD variable line look like this:`REC_CARD=default`
2. Set the CHANNELS variable line to look like this:`CHANNELS=2`
3. And then you can either restart the services manually:`sudo systemctl restart livestream.service && sudo systemctl restart birdnet_recording.service`, or you can simply reboot.
4. Check the logs at http://birdlog.local to see if the complaints about not finding files persists. Note there will be complaints about not finding things from previous days, but they make sense and are harmless at this point. You may also follow the _birdnet_recording.service_ logs in the terminal via `journalctl -fu birdnet_recording.service`

I hope that's not too much information for what is ultimately a 4-step answer, but I wanted you to know what is going on. 

My best ~
Patrick

**Comment by mcguirepr89** [comment]
Hi Robin,
I just wanted to follow up on this to see if you've had any success?

My best,
Patrick

**Comment by robinsandfort** [comment]
Hi Patrick,
after editing the config file it seemed to work but
the .wav files were silent so no detections happend. Karl (using the same mic) send me his ~/BirdNET-system/soundcard_params.txt
and this did the trick. Maybe I would have also reached there by a fresh install. Karl and I keep testing and will keep you updated.
Thanks for helping us out!
Greetings,
Robin

**Comment by DD4WH** [comment]
@robinsandfort 
Maybe you would like to add your type of USB mic and the specific soundcard_params.txt to this thread, so others can learn from it?
https://github.com/mcguirepr89/BirdNET-system/discussions/26

**Comment by mcguirepr89** [comment]
@robinsandfort Greetings! I wanted to follow up with you to ask if I can add you (and Karl?) to [the list of locations BirdNET-system is listening](https://github.com/mcguirepr89/BirdNET-system/wiki)? If so, please just let me know what location (as specific or general as you'd like) and what name you would like to use.
My best,
Patrick

**Comment by robinsandfort** [comment]
@mcguirepr89 Hi Patrick, I´m using your BirdNET-system in the Donau-Auen east of Vienna, Austria. You can use my name Robin Sandfort. I´ll try the German names next.

**Comment by mcguirepr89** [comment]
No longer an issue
